context:
  version: "0.29.0"

package:
  name: prettierd
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@fsouza/prettierd/-/prettierd-${{ version }}.tgz
  sha256: 3195a481ed2a020deb12f60a9c61dcc8051a4cd5401da7fa7c4596afb5b1fc68

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prettierd --help

about:
  license: ISC
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: prettier, as a daemon, for ludicrous formatting speed
  homepage: https://github.com/fsouza/prettierd
  repository: https://github.com/fsouza/prettierd

extra:
  recipe-maintainers:
    - danielnachun
