context:
  version: "0.27.0"

package:
  name: prettierd
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@fsouza/prettierd/-/prettierd-${{ version }}.tgz
  sha256: a7a3b95cddf5860d315ccfaaf9df26eee4e7631534f427f68bfb7d1d182a163b

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prettierd --help

about:
  license: ISC
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: prettier, as a daemon, for ludicrous formatting speed
  homepage: https://github.com/fsouza/prettierd
  repository: https://github.com/fsouza/prettierd

extra:
  recipe-maintainers:
    - danielnachun
