context:
  version: "0.28.0"

package:
  name: prettierd
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@fsouza/prettierd/-/prettierd-${{ version }}.tgz
  sha256: 944799736015578fdff5ba50dcf200eb052bec3cddfaf922c938867962d6b04a

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prettierd --help

about:
  license: ISC
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: prettier, as a daemon, for ludicrous formatting speed
  homepage: https://github.com/fsouza/prettierd
  repository: https://github.com/fsouza/prettierd

extra:
  recipe-maintainers:
    - danielnachun
